### ISSUE TITLE
Dont open

### ISSUE THREAD

**Issue by Mafiaproo** [PolyhedralDev/NoiseTool#13]
Hello I start the .jar but nothing happend

i even tried java -jar NoiseTool-1.1.1-all.jar 
but i got this error :`java -jar NoiseTool-1.1.1-all.jar
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because "retVal" is null
        at java.desktop/sun.awt.shell.Win32ShellFolder2$MultiResolutionIconImage.getResolutionVariant(Win32ShellFolder2.java:1459)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$MultiResolutionIconImage.getBaseImage(Win32ShellFolder2.java:1438)
        at java.desktop/java.awt.image.AbstractMultiResolutionImage.getProperty(AbstractMultiResolutionImage.java:140)
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:255)
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:241)
        at java.desktop/javax.swing.filechooser.FileSystemView.getSystemIcon(FileSystemView.java:252)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI$WindowsFileView.getIcon(WindowsFileChooserUI.java:1360)
        at java.desktop/javax.swing.JFileChooser.getIcon(JFileChooser.java:1613)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI$DirectoryComboBoxRenderer.getListCellRendererComponent(WindowsFileChooserUI.java:1055)
        at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
        at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
        at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:231)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:206)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:258)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:459)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:469)
        at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:513)
        at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1281)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1097)
        at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1257)
        at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1318)
        at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1365)
        at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI$DirectoryComboBoxModel.setSelectedItem(WindowsFileChooserUI.java:1198)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI$DirectoryComboBoxModel.addItem(WindowsFileChooserUI.java:1169)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI.doDirectoryChanged(WindowsFileChooserUI.java:785)
        at java.desktop/com.sun.java.swing.plaf.windows.WindowsFileChooserUI$11.propertyChange(WindowsFileChooserUI.java:876)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
        at java.desktop/java.awt.Component.firePropertyChange(Component.java:8717)
        at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:610)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:364)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:310)
        at com.dfsek.noise.NoiseTool.<init>(NoiseTool.java:50)
        at com.dfsek.noise.NoiseTool.lambda$main$0(NoiseTool.java:176)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by solonovamax** [comment]
tbh, I'm curious how this even happens.
It definitely is windows-specific, so someone on windows would need to test it.

But I feel like this is definitely some issue with how windows is handling things, as it produces the error due to some `Win32ShellFolder2` class.

**Comment by solonovamax** [comment]
Looking at the code for `Win32ShellFolder2`, this seems to suggest that it's trying to get an icon which does not exist?

https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.desktop/windows/classes/sun/awt/shell/Win32ShellFolder2.java#L1443-L1468:
> ```java
> int dist = 0;
> Image retVal = null;
> // We only care about width since we don't support non-square icons
> int w = (int) width;
> int retindex = 0;
> for (Integer i : resolutionVariants.keySet()) {
>     if (retVal == null || dist > Math.abs(i - w)
>             || (dist == Math.abs(i - w) && i > retindex)) {
>         retindex = i;
>         dist = Math.abs(i - w);
>         retVal = resolutionVariants.get(i);
>         if (i == w) {
>             break;
>         }
>     }
> }
> if (retVal.getWidth(null) != w) {
>     BufferedImage newVariant = new BufferedImage(w, w, BufferedImage.TYPE_INT_ARGB);
>     Graphics2D g2d = newVariant.createGraphics();
>     g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
>     g2d.drawImage(retVal, 0,0, w, w, null);
>     g2d.dispose();
>     resolutionVariants.put(w, newVariant);
>     retVal = newVariant;
> }
> return retVal;
> ```

I'm guessing that you're using a jdk ~ 21, as in jdk 17 it seems it just returns `retVal` directly rather than attempting to invoke `getWidth` on it:
https://github.com/openjdk/jdk/blob/jdk-17%2B35/src/java.desktop/windows/classes/sun/awt/shell/Win32ShellFolder2.java#L1417-L1433:
> ```java
> int dist = 0;
> Image retVal = null;
> // We only care about width since we don't support non-rectangular icons
> int w = (int) width;
> int retindex = 0;
> for (Integer i : resolutionVariants.keySet()) {
>     if (retVal == null || dist > Math.abs(i - w)
>             || (dist == Math.abs(i - w) && i > retindex)) {
>         retindex = i;
>         dist = Math.abs(i - w);
>         retVal = resolutionVariants.get(i);
>         if (i == w) {
>             break;
>         }
>     }
> }
> return retVal;
> ```

if you're able to reproduce this with the latest jdk/jre, then this is almost certainly caused by a bug in the jdk and should be reported here: https://bugs.openjdk.org/projects/JDK/issues

**Comment by solonovamax** [comment]
> Just gave it a try, works just fine for me Any chance you're using the java JRE instead of the JDK?


tbh I feel it's more likely that they're using an old java 21 jdk or there's smth funny with their windows install

**Comment by Mafiaproo** [comment]
Hi,
This is my java version : 
`C:\Users\gamer>java -version
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)`

Im on Win11 (Version	10.0.22631 Build 22631)
Im using Terra-bukkit-6.4.3-BETA+ab60f14ff-shaded

Did I need to put noisetool on the terra config plugin to work?

**Comment by Mafiaproo** [comment]
Every time i launch noisetool it do not create a addon folder
So i created it my self and i copy paste the entirely of the terra addons

**Comment by solonovamax** [comment]
> Every time i launch noisetool it do not create a addon folder
> So i created it my self and i copy paste the entirely of the terra addons

- is that error the *entirety* of the log output?
- have you modified your base windows installation at all (installing programs does not count. I'm specifically asking about a custom iso, removing core components, and/or deleting files/folders in windows-owned directories like system32)
- can you reproduce this with the latest java lts version (latest java 21 version) or the latest java major version (latest java 23 version)
