### ISSUE TITLE
v1.0.1 doesn't show window

### ISSUE THREAD

**Issue by AverageTurtle** [PolyhedralDev/NoiseTool#8]
I'm on windows 10 (version 22H2). When I double click the jar nothing happens. However I cannot delete or move the file because it says it is open by Java runtime. Looking in task manager I was not able to find it which was odd. v1.0.0 works fine for me so I'm not sure what the issue is.

**Comment by Trainzack** [comment]
I have the same issue. When running from CLI, I get this exception:
```
Exception in thread "AWT-EventQueue-0" java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Program Files\Eclipse Adoptium\jre-21.0.1.12-hotspot\bin\.\addons
        at com.dfsek.terra.addon.BootstrapAddonLoader.loadAddons(BootstrapAddonLoader.java:96)
        at com.dfsek.terra.AbstractPlatform.loadAddons(AbstractPlatform.java:180)
        at com.dfsek.noise.platform.PlatformImpl.<init>(PlatformImpl.java:12)
        at com.dfsek.noise.NoiseTool.<init>(NoiseTool.java:74)
        at com.dfsek.noise.NoiseTool.lambda$main$0(NoiseTool.java:166)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Eclipse Adoptium\jre-21.0.1.12-hotspot\bin\.\addons
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectories(Unknown Source)
        at com.dfsek.terra.addon.BootstrapAddonLoader.loadAddons(BootstrapAddonLoader.java:85)
```
This exception does not terminate the process.

**Comment by solonovamax** [comment]
lmao why does it think that the process' directory is in the jdk bin dir

**Comment by duplexsystem** [comment]
Hi i think the issue if you don't have the addons needed to run noise tool. These can be gotten from a Terra Jar published to Modrinth. You can ask for help on discord or matrix if you need it!

**Comment by solonovamax** [comment]
@duplexsystem it seems to be attempting to load the addons from within the `JDK_HOME` directory:
> ```
java.nio.file.AccessDeniedException: C:\Program Files\Eclipse Adoptium\jre-21.0.1.12-hotspot\bin\.\addons
```
